name: flutter_base_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  dio: ^5.8.0+1
  go_router: ^16.2.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  freezed: ^2.5.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
